// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbkjiplVzV1FZDc2NthAqsaHRaWA9xWU',
    appId: '1:958799227985:web:603f79dd022d61c61ddc70',
    messagingSenderId: '958799227985',
    projectId: 'backend-demo-900a7',
    authDomain: 'backend-demo-900a7.firebaseapp.com',
    databaseURL: 'https://backend-demo-900a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-demo-900a7.firebasestorage.app',
    measurementId: 'G-MD8640SFG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXNJ8cPDmxrKQV8IFTAi0B2tWlcQhQ1cY',
    appId: '1:958799227985:android:45a7d9fa7f68c7011ddc70',
    messagingSenderId: '958799227985',
    projectId: 'backend-demo-900a7',
    databaseURL: 'https://backend-demo-900a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-demo-900a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWye3hVz8sSp0wXIZMqaSdr1bOX0PUrO8',
    appId: '1:958799227985:ios:14506ddf464bac991ddc70',
    messagingSenderId: '958799227985',
    projectId: 'backend-demo-900a7',
    databaseURL: 'https://backend-demo-900a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-demo-900a7.firebasestorage.app',
    iosBundleId: 'com.example.s1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWye3hVz8sSp0wXIZMqaSdr1bOX0PUrO8',
    appId: '1:958799227985:ios:14506ddf464bac991ddc70',
    messagingSenderId: '958799227985',
    projectId: 'backend-demo-900a7',
    databaseURL: 'https://backend-demo-900a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-demo-900a7.firebasestorage.app',
    iosBundleId: 'com.example.s1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKbkjiplVzV1FZDc2NthAqsaHRaWA9xWU',
    appId: '1:958799227985:web:8c027dc51c6dc8671ddc70',
    messagingSenderId: '958799227985',
    projectId: 'backend-demo-900a7',
    authDomain: 'backend-demo-900a7.firebaseapp.com',
    databaseURL: 'https://backend-demo-900a7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-demo-900a7.firebasestorage.app',
    measurementId: 'G-5DP1RC47XN',
  );
}
