// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1mMP2cqeABeKOzuGN2dCTrepmyVb-Lzs',
    appId: '1:917377388614:web:cd1d5592a83bf03ea6ba47',
    messagingSenderId: '917377388614',
    projectId: 'mae-group26',
    authDomain: 'mae-group26.firebaseapp.com',
    storageBucket: 'mae-group26.firebasestorage.app',
    measurementId: 'G-QEREGW17KP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7Hf1H88lW7WHA2QpA94o2mDVu9hbitHU',
    appId: '1:917377388614:android:b4d48210030da1ffa6ba47',
    messagingSenderId: '917377388614',
    projectId: 'mae-group26',
    storageBucket: 'mae-group26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYYBS5NPHYNwJi-vaeqyy8MWPEIPoXrpE',
    appId: '1:917377388614:ios:e83b673e726ca9e5a6ba47',
    messagingSenderId: '917377388614',
    projectId: 'mae-group26',
    storageBucket: 'mae-group26.firebasestorage.app',
    iosBundleId: 'com.example.addMap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYYBS5NPHYNwJi-vaeqyy8MWPEIPoXrpE',
    appId: '1:917377388614:ios:e83b673e726ca9e5a6ba47',
    messagingSenderId: '917377388614',
    projectId: 'mae-group26',
    storageBucket: 'mae-group26.firebasestorage.app',
    iosBundleId: 'com.example.addMap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1mMP2cqeABeKOzuGN2dCTrepmyVb-Lzs',
    appId: '1:917377388614:web:d820c9c8eef8d601a6ba47',
    messagingSenderId: '917377388614',
    projectId: 'mae-group26',
    authDomain: 'mae-group26.firebaseapp.com',
    storageBucket: 'mae-group26.firebasestorage.app',
    measurementId: 'G-TJKLR1CJ8L',
  );
}
