// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4RjRGWLKI9pgzWJXv8gDt9mIEsVsUkWo',
    appId: '1:1065736234333:web:74033b2983a8e5c315b4b4',
    messagingSenderId: '1065736234333',
    projectId: 'test3-assignment-config',
    authDomain: 'test3-assignment-config.firebaseapp.com',
    storageBucket: 'test3-assignment-config.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvHbChQi0O93PTpljuIEyY04go8pBlurQ',
    appId: '1:1065736234333:android:b4d8aae65d7b1cd815b4b4',
    messagingSenderId: '1065736234333',
    projectId: 'test3-assignment-config',
    storageBucket: 'test3-assignment-config.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4RjRGWLKI9pgzWJXv8gDt9mIEsVsUkWo',
    appId: '1:1065736234333:web:c0ebf282d74451f715b4b4',
    messagingSenderId: '1065736234333',
    projectId: 'test3-assignment-config',
    authDomain: 'test3-assignment-config.firebaseapp.com',
    storageBucket: 'test3-assignment-config.firebasestorage.app',
  );
}
